spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sunote
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Redis配置
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:  # 无密码时留空
      timeout: 5000
      database: 0  # 使用的数据库索引，默认为0

  mail:
    host: smtp.qq.com              # 根据邮箱服务商选择（QQ、163、Gmail等）
    port: 587
    username: example@qq.com    # 发件人邮箱
    password: example       # 邮箱授权码（不是登录密码）
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# 京东云OSS配置
oss:
  access-key: example     # 实际应用中替换为真实的访问密钥
  secret-key: example     # 实际应用中替换为真实的密钥
  endpoint: s3.cn-south-1.jdcloud-oss.com
  bucket: example
  region: cn-south-1
  # 文件访问URL前缀
  url-prefix: https://example.s3.cn-south-1.jdcloud-oss.com/

server:
  address: 0.0.0.0
  port: 10800
